apiVersion: app/v1
kind: Deployment
metadata:
  name: abelqasm-app
  labels:
    app: abelqasm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abelqasm
  template:
    metadata:
      labels:
        app: abelqasm
    spec:
      containers:
      - name: abelqasm
        image: wil42/playground:v1
        ports:
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will-service
spec:
  selector:
    app: abelqasm
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
